---

# Variables definition
# Pycharm, target and working directories: C:\Users\victorm\PycharmProjects\pythonProject1\auto
# set working dir below to be same as this
# Version label

dirs:
  working: !!str "C:\\Users\\victorm\\PycharmProjects\\pythonProject1\\auto\\"  # note above wrt PyCharm working + target directories
  
urls:
  AWE: !!str "https://wfo.a31.verintcloudservices.com/wfo/control/signin"       # SSO logon Tenant admin T1
  AWE_dash: !!str "https://wfo.a31.verintcloudservices.com/wfo/ui"              # used after initial login context saved
  AWE_T0: !!str "https://wfo.a31.verintcloudservices.com/wfo/control/dbrealmsignin"     # dbrealm signin, T0

# AWE credentials tenant admin, T0 admin
logon:
  USERNAME_TA : !!str "admin01@verintnew01.prodreleasev2.com"     # tenant admin
  PASSWORD_TA : !!str "Verint.123!!"
  USERNAME_T0 : !!str "admin01@avaya.com"     # tenant admin
  PASSWORD_T0 : !!str "1_Abc_123"


  

# LOG LEVELS
# Level	Numeric Value	Description
# Critical	50	Highest severity messages; may cause a program to crash or exit.
# Error	40	High severity messages generally related to an operation failing that does not cause the program to crash or exit.
# Warning	30	Potentially negative events that may cause abnormal operation or otherwise require attention (such as the use of a deprecated API).
# Info	20	Messages that log standard/expected events.
# Debug	10	Messages useful for debugging how an application is running.
# Notset	0	Default level when a new logger is created. Setting the root logger to NOTSET logs all messages. For other loggers, NOTSET messages are delegated to parent loggers until a level other than NOTSET is found.

#T1 tests:
#1: SignOnWebpageTitle
#2: Usernnme_logon_filed_available
#3: WFO_Version_frontPage
#4: Tenant_admin_signin
#5: accessInteractionsSearchPage
#6: searchCallsLast7d
#7: searchCallFromToday 
#8: searchCallDateString ( defined config.yaml)
#9: searchCallUserString ( defined config.yaml)
#10: logout

#T0 tests:
#1: SignOnWebpageTitle
#2: Usernnme_logon_filed_available
#3: WFO_Version_frontPage
#4: Tenant_admin_signin